### ISSUE TITLE
Update lodash version >= 4.17.11 to avoid npm audit warnings

### ISSUE THREAD

**Issue by michaelfarrell76** [nknapp/multilang-extract-comments#11]
See the [npm advisory](https://www.npmjs.com/advisories/782)

Simply need to update lodash>= 4.17.5

**Comment by jhnferraris** [comment]
Is someone still maintaining this repository?

**Comment by seancsnyder** [comment]
Eh, kinda. Not very actively though.

**Comment by jhnferraris** [comment]
@seancsnyder Alright. Is the npm package updated? Let us know. Thanks

**Comment by seancsnyder** [comment]
Just published to npm. https://www.npmjs.com/package/multilang-extract-comments

**Comment by jhnferraris** [comment]
Thank you!
