### ISSUE TITLE
New file types

### ISSUE THREAD

**Issue by ScottDillman** [nknapp/multilang-extract-comments#6]
Is there a clean way of adding support for new file types not supported by comment-patterns? I have a few in-house file types I would dynamically like to add support for but having a hard time finding the right place to hook into the process.

**Comment by nknapp** [comment]
I'm afraid that, at the moment, the only way is to fork both `comment-patterns` and `multilang-extract-comments`. There are no extension points. 

This could be made possible by using the `options`-argument to provide a list of language-definitions that could be evaluated [here](https://github.com/nknapp/multilang-extract-comments/blob/master/index.js#L25).  [require('comment-patterns/build/variations/regexes')](https://github.com/nknapp/comment-patterns/blob/master/build/variations/regexes.js) could be used to compile the patterns into [this format](https://github.com/nknapp/comment-patterns#variation-regex) which is what `multilang-extract-comments` needs. 

If you want to create a PR, please do so.

**Comment by ScottDillman** [comment]
Ok.. thanks. If I end up going that route I'll submit a PR

**Comment by nknapp** [comment]
Merged (#7) and published (0.3.0)

**Comment by nknapp** [comment]
@CTrauma Thanks for this contribution. I would also invite you as owner on npm. I am hardly using this package anymore and I think it would be a good idea give you contributors the ability to publish on npm, in case I am not available for some reason.

Do you have an account on npmjs.com?
