### ISSUE TITLE
Support for template strings?

### ISSUE THREAD

**Issue by danShumway** [nknapp/multilang-extract-comments#9]
Template strings allow nesting functions (and even other template strings):

``var x = `here is a ${`template`} string with ${`multiple ${ (function () { return `nested`}()) } ` } parts`;``

Correct me if I'm wrong, but it doesn't look like there's [currently](https://github.com/nknapp/multilang-extract-comments/blob/master/spec/javascript-spec.js) support for this syntax? What would be the biggest hurdle to handling complex syntax like this?

If it's not too much of a rewrite, maybe I could try my hand at adding support.

**Comment by nknapp** [comment]
The fact, that the extractor is based wholely on regular expressions, makes it difficult to parse something like that. I don't think it is possible without using a real JavaScript parser. But that would require having a parser for every other language as well.
Not the purpose of this tiny library.

If you have an idea, you can give it a try, and if it works, I will merge it.

But personally, if have gone back to using jsdoc for extracting comments from JavaScript. E.g. in the project "thought-plugin-jsdoc"

Sorry for the delay, I hadn't my email configured with so my first answer wasn't accepted by github

**Comment by danShumway** [comment]
Fair enough. If I get an idea I'll update, but that's roughly in line with what I've been seeing from other comment extractors as well.
